version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - database
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "true"

  database:
    build: ./march_22a
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: myappdb
      MYSQL_USER: myappuser
      MYSQL_PASSWORD: myappw
    
